SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS  `product_picture`;
CREATE TABLE `product_picture` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `product_picture` char(200) DEFAULT NULL,
  `intro` text,
  PRIMARY KEY (`id`),
  KEY `FK_product_id` (`product_id`),
  CONSTRAINT `FK_product_id` FOREIGN KEY (`product_id`) REFERENCES `product` (`product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8;

insert into `product_picture`(`id`,`product_id`,`product_picture`,`intro`) values
(1,1,'public/imgs/phone/picture/Redmi-k30-1.png',null),
(2,1,'public/imgs/phone/picture/Redmi-k30-2.png',null),
(3,1,'public/imgs/phone/picture/Redmi-k30-3.png',null),
(4,1,'public/imgs/phone/picture/Redmi-k30-4.png',null),
(5,1,'public/imgs/phone/picture/Redmi-k30-5.png',null),
(6,2,'public/imgs/phone/picture/Redmi K30 5G-1.jpg',null),
(7,2,'public/imgs/phone/picture/Redmi K30 5G-2.jpg',null),
(8,2,'public/imgs/phone/picture/Redmi K30 5G-3.jpg',null),
(9,2,'public/imgs/phone/picture/Redmi K30 5G-4.jpg',null),
(10,2,'public/imgs/phone/picture/Redmi K30 5G-5.jpg',null),
(11,3,'public/imgs/phone/picture/MI CC9 Pro-1.jpg',null),
(12,3,'public/imgs/phone/picture/MI CC9 Pro-2.jpg',null),
(13,3,'public/imgs/phone/picture/MI CC9 Pro-3.jpg',null),
(14,3,'public/imgs/phone/picture/MI CC9 Pro-4.jpg',null),
(15,3,'public/imgs/phone/picture/MI CC9 Pro-5.jpg',null),
(16,3,'public/imgs/phone/picture/MI CC9 Pro-6.jpg',null),
(17,4,'public/imgs/phone/picture/Redmi 8-1.jpg',null),
(18,4,'public/imgs/phone/picture/Redmi 8-2.jpg',null),
(19,4,'public/imgs/phone/picture/Redmi 8-3.jpg',null),
(20,4,'public/imgs/phone/picture/Redmi 8-4.jpg',null),
(21,4,'public/imgs/phone/picture/Redmi 8-5.jpg',null),
(22,5,'public/imgs/phone/picture/Redmi 8A-1.jpg',null),
(23,6,'public/imgs/phone/picture/Redmi Note8 Pro-1.png',null),
(24,6,'public/imgs/phone/picture/Redmi Note8 Pro-2.png',null),
(25,6,'public/imgs/phone/picture/Redmi Note8 Pro-3.png',null),
(26,6,'public/imgs/phone/picture/Redmi Note8 Pro-4.png',null),
(27,6,'public/imgs/phone/picture/Redmi Note8 Pro-5.png',null),
(28,7,'public/imgs/phone/picture/Redmi Note8-1.jpg',null),
(29,7,'public/imgs/phone/picture/Redmi Note8-2.jpg',null),
(30,7,'public/imgs/phone/picture/Redmi Note8-3.jpg',null),
(31,7,'public/imgs/phone/picture/Redmi Note8-4.jpg',null),
(32,7,'public/imgs/phone/picture/Redmi Note8-5.jpg',null),
(33,8,'public/imgs/phone/picture/Redmi 7A-1.jpg',null),
(34,8,'public/imgs/phone/picture/Redmi 7A-2.jpg',null),
(35,8,'public/imgs/phone/picture/Redmi 7A-3.jpg',null),
(36,8,'public/imgs/phone/picture/Redmi 7A-4.jpg',null),
(37,8,'public/imgs/phone/picture/Redmi 7A-5.jpg',null),
(38,9,'public/imgs/phone/picture/MiTv-4A-32-1.jpg',null),
(39,9,'public/imgs/phone/picture/MiTv-4A-32-2.jpg',null),
(40,9,'public/imgs/phone/picture/MiTv-4A-32-3.jpg',null),
(41,9,'public/imgs/phone/picture/MiTv-4A-32-4.jpg',null),
(42,10,'public/imgs/phone/picture/MiTv-E55A-1.jpg',null),
(43,10,'public/imgs/phone/picture/MiTv-E55A-2.jpg',null),
(44,10,'public/imgs/phone/picture/MiTv-E55A-3.jpg',null),
(45,10,'public/imgs/phone/picture/MiTv-E55A-4.jpg',null),
(46,11,'public/imgs/phone/picture/MiTv-E65A-1.jpg',null),
(47,11,'public/imgs/phone/picture/MiTv-E65A-2.jpg',null),
(48,11,'public/imgs/phone/picture/MiTv-E65A-3.jpg',null),
(49,11,'public/imgs/phone/picture/MiTv-E65A-4.jpg',null),
(50,12,'public/imgs/phone/picture/MiTv-4X 43-1.jpg',null),
(51,12,'public/imgs/phone/picture/MiTv-4X 43-2.jpg',null),
(52,12,'public/imgs/phone/picture/MiTv-4X 43-3.jpg',null),
(53,13,'public/imgs/phone/picture/MiTv-4C 55-1.jpg',null),
(54,13,'public/imgs/phone/picture/MiTv-4C 55-2.jpg',null),
(55,13,'public/imgs/phone/picture/MiTv-4C 55-3.jpg',null),
(56,14,'public/imgs/phone/picture/MiTv-4A 65-1.jpg',null),
(57,15,'public/imgs/phone/picture/MiTv-ArtTv-65-1.jpg',null),
(58,16,'public/imgs/phone/picture/AirCondition-V1C1-1.jpg',null),
(59,17,'public/imgs/phone/picture/AirCondition-F3W1-1.jpg',null),
(60,18,'public/imgs/phone/picture/Washer-Pro-10-1.jpg',null),
(61,18,'public/imgs/phone/picture/Washer-Pro-10-2.jpg',null),
(62,18,'public/imgs/phone/picture/Washer-Pro-10-3.jpg',null),
(63,18,'public/imgs/phone/picture/Washer-Pro-10-4.jpg',null),
(64,19,'public/imgs/phone/picture/protectingShell-RedMi-K20&pro-1.jpg',null),
(65,20,'public/imgs/phone/picture/protectingShell-Mi-9-1.jpg',null),
(66,20,'public/imgs/phone/picture/protectingShell-Mi-9-2.jpg',null),
(67,21,'public/imgs/phone/picture/protectingMen-Mi-CC9-1.jpg',null),
(68,22,'public/imgs/phone/picture/protectingMen-Mi-CC9e-1.jpg',null),
(69,23,'public/imgs/phone/picture/charger-30w-1.jpg',null),
(70,23,'public/imgs/phone/picture/charger-30w-2.jpg',null),
(71,23,'public/imgs/phone/picture/charger-30w-3.jpg',null),
(72,23,'public/imgs/phone/picture/charger-30w-4.jpg',null),
(73,24,'public/imgs/phone/picture/charger-18w-1.jpg',null),
(74,24,'public/imgs/phone/picture/charger-18w-2.jpg',null),
(75,24,'public/imgs/phone/picture/charger-18w-3.jpg',null),
(76,25,'public/imgs/phone/picture/charger-60w-1.jpg',null),
(77,25,'public/imgs/phone/picture/charger-60w-2.jpg',null),
(78,25,'public/imgs/phone/picture/charger-60w-3.jpg',null),
(79,25,'public/imgs/phone/picture/charger-60w-4.jpg',null),
(80,26,'public/imgs/phone/picture/charger-36w-1.jpg',null),
(81,26,'public/imgs/phone/picture/charger-36w-2.jpg',null),
(82,26,'public/imgs/phone/picture/charger-36w-3.jpg',null),
(83,26,'public/imgs/phone/picture/charger-36w-4.jpg',null),
(84,26,'public/imgs/phone/picture/charger-36w-5.jpg',null),
(85,27,'public/imgs/phone/picture/charger-car-1.jpg',null),
(86,27,'public/imgs/phone/picture/charger-car-2.jpg',null),
(87,27,'public/imgs/phone/picture/charger-car-3.jpg',null),
(88,27,'public/imgs/phone/picture/charger-car-4.jpg',null),
(89,27,'public/imgs/phone/picture/charger-car-5.jpg',null),
(90,27,'public/imgs/phone/picture/charger-car-6.jpg',null),
(91,28,'public/imgs/phone/picture/charger-car-37w-1.jpg',null),
(92,28,'public/imgs/phone/picture/charger-car-37w-2.jpg',null),
(93,28,'public/imgs/phone/picture/charger-car-37w-3.jpg',null),
(94,28,'public/imgs/phone/picture/charger-car-37w-4.jpg',null),
(95,28,'public/imgs/phone/picture/charger-car-37w-5.jpg',null),
(96,29,'public/imgs/phone/picture/charger-tio-1.jpg',null),
(97,29,'public/imgs/phone/picture/charger-tio-2.jpg',null),
(98,29,'public/imgs/phone/picture/charger-tio-3.jpg',null),
(99,29,'public/imgs/phone/picture/charger-tio-4.jpg',null),
(100,29,'public/imgs/phone/picture/charger-tio-5.jpg',null),
(101,30,'public/imgs/phone/picture/charger-10000mAh-1.jpg',null),
(102,30,'public/imgs/phone/picture/charger-10000mAh-2.jpg',null),
(103,30,'public/imgs/phone/picture/charger-10000mAh-3.jpg',null),
(104,30,'public/imgs/phone/picture/charger-10000mAh-4.jpg',null),
(105,30,'public/imgs/phone/picture/charger-10000mAh-5.jpg',null),
(106,31,'public/imgs/phone/picture/protectingShell-Mi-CC9Pro-1.jpg',null),
(107,32,'public/imgs/phone/picture/protectingShell-RedMi-K20-1.jpg',null),
(108,33,'public/imgs/phone/picture/protectingShell-Mi-9SE-1.jpg',null),
(109,34,'public/imgs/phone/picture/protectingShell-Mi-9-red-1.jpg',null),
(110,35,'public/imgs/phone/picture/protectingShell-Mix-3-1.jpg',null);
SET FOREIGN_KEY_CHECKS = 1;

